version: "2"

services:
    nginx:
        build:
            context: ./docker/nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html

    fpm:
        build:
            context: ./docker/php
        volumes:
            - .:/var/www/html
        expose:
            - "9000"
        environment:
            - "DB_HOST=db"

    db:
        build:
            context: ./docker/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=rootpass

    composer:
        image: composer:latest
        volumes:
          - .:/app